const mongoose = require('mongoose');

const postSchema = new mongoose.Schema({
    userId: {
        type: String,
        required: true
    },
    userImage: {
        type: String,
        default: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/User_icon_2.svg/330px-User_icon_2.svg.png'
    },
    //! postId is generated by the frontend to achieve real time communication between server & client. :)
    postId: {
        type: String,
        required: true
    },
    title: {
        type: String,
        required: true,
    },
    description: {
        type: String,
        required: true,
    },

    isImage: {
        type: Boolean,
        default: false
    },

    imagePath: {
        type: String,
        default: '',
    },

    likes: [{ type: String, required: true }],

    comments: [{
        user: { type: String, required: true },
        text: { type: String, required: true },
        createdAt: { type: Date, default: Date.now }
    }],

    createdAt: { type: Date, default: Date.now }

});

module.exports = mongoose.model("Post", postSchema);